// const debugCont = {};

// /* ***************************
//  *  Intentional error generator
//  *  This controller intentionally throws an error to test the
//  *  application's error handling middleware and error view.
//  * ************************** */
// debugCont.causeError = async function (req, res, next) {
//   // Throwing an exception here will be caught by the
//   // utilities.handleErrors wrapper and passed to the error middleware.
//   throw new Error("Intentional server error for testing (500)");
// };

// module.exports = debugCont;
